// Device-owner credential storage. Keys never enter SwiftData/UserDefaults and
// use ThisDeviceOnly accessibility so a backup restore cannot clone ownership.
import Foundation
import Security

protocol KeychainClient {
    func copyMatching(_ query: CFDictionary) -> (OSStatus, CFTypeRef?)
    func update(_ query: CFDictionary, attributes: CFDictionary) -> OSStatus
    func add(_ query: CFDictionary) -> OSStatus
    func delete(_ query: CFDictionary) -> OSStatus
}

struct SystemKeychainClient: KeychainClient {
    func copyMatching(_ query: CFDictionary) -> (OSStatus, CFTypeRef?) {
        var result: CFTypeRef?
        return (SecItemCopyMatching(query, &result), result)
    }
    func update(_ query: CFDictionary, attributes: CFDictionary) -> OSStatus {
        SecItemUpdate(query, attributes)
    }
    func add(_ query: CFDictionary) -> OSStatus { SecItemAdd(query, nil) }
    func delete(_ query: CFDictionary) -> OSStatus { SecItemDelete(query) }
}

enum OwnerCredentialDeletionError: LocalizedError, Equatable {
    case deletionFailed(status: OSStatus)
    case verificationFailed
    case verificationUnavailable(status: OSStatus)

    var errorDescription: String? {
        switch self {
        case .deletionFailed(let status):
            "Keychain refused to delete the owner credential (status \(status))."
        case .verificationFailed:
            "The owner credential remained in Keychain after deletion."
        case .verificationUnavailable(let status):
            "Keychain could not verify credential deletion (status \(status))."
        }
    }
}

enum ProMistLocalDataDeletionError: LocalizedError {
    case credentials([UInt64: OwnerCredentialDeletionError])

    var errorDescription: String? {
        switch self {
        case .credentials(let failures):
            let devices = failures.keys.sorted().map(String.init).joined(separator: ", ")
            return "Owner credentials could not be removed for device IDs \(devices). Local fan records were preserved so deletion can be retried."
        }
    }
}

/// Explicit compensating transaction for the Keychain/SwiftData boundary.
/// The persistent record is touched only after the security deletion reports
/// verified absence. If record deletion later fails, retry remains safe because
/// an already-missing Keychain item is a successful state.
@MainActor
enum LocalDeviceRemovalCoordinator {
    static func remove(
        securityDeletionRequired: Bool,
        deleteCredential: () throws -> Void,
        deletePersistentRecord: () throws -> Void
    ) throws {
        if securityDeletionRequired { try deleteCredential() }
        try deletePersistentRecord()
    }
}

@MainActor
enum OwnerCredentialStore {
    private static let service = "com.demo.ProMist.owner"
    static var client: any KeychainClient = SystemKeychainClient()

    /// Loads the 32-byte owner key bound to the complete firmware device ID.
    /// - Parameter deviceID: Authoritative 64-bit identity, never a name suffix.
    /// - Returns: The validated key or `nil` for missing/malformed Keychain data.
    static func load(deviceID: UInt64) -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: String(deviceID),
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        let (status, result) = client.copyMatching(query as CFDictionary)
        guard status == errSecSuccess,
              let data = result as? Data, data.count == 32 else { return nil }
        return data
    }

    /// Replaces the credential for a device with a device-only Keychain item.
    /// - Parameters:
    ///   - key: Exactly 32 random bytes generated by the firmware.
    ///   - deviceID: Full identity used as the Keychain account.
    /// - Returns: Whether Keychain accepted the new item.
    static func save(_ key: Data, deviceID: UInt64) -> Bool {
        guard key.count == 32 else { return false }
        let identity: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: String(deviceID)
        ]
        let update: [String: Any] = [
            kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,
            kSecValueData as String: key
        ]
        let status = client.update(
            identity as CFDictionary,
            attributes: update as CFDictionary
        )
        if status == errSecSuccess { return true }
        guard status == errSecItemNotFound else { return false }
        var item = identity
        update.forEach { item[$0.key] = $0.value }
        return client.add(item as CFDictionary) == errSecSuccess
    }

    /// Deletes a device credential and verifies that no matching item remains.
    ///
    /// `errSecItemNotFound` is treated as successful, idempotent absence.
    /// - Throws: ``OwnerCredentialDeletionError`` when deletion or verification
    ///   cannot establish that the credential is gone.
    static func delete(deviceID: UInt64) throws {
        let identity: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: String(deviceID)
        ]
        let status = client.delete(identity as CFDictionary)
        guard status == errSecSuccess || status == errSecItemNotFound else {
            throw OwnerCredentialDeletionError.deletionFailed(status: status)
        }

        var verification = identity
        verification[kSecReturnData as String] = true
        verification[kSecMatchLimit as String] = kSecMatchLimitOne
        let (verificationStatus, _) = client.copyMatching(
            verification as CFDictionary
        )
        switch verificationStatus {
        case errSecItemNotFound:
            return
        case errSecSuccess:
            throw OwnerCredentialDeletionError.verificationFailed
        default:
            throw OwnerCredentialDeletionError.verificationUnavailable(
                status: verificationStatus
            )
        }
    }

    /// Attempts every distinct nonzero device ID and reports all failures
    /// together so callers can preserve the affected SwiftData records.
    static func deleteAll(deviceIDs: some Sequence<UInt64>) throws {
        var failures: [UInt64: OwnerCredentialDeletionError] = [:]
        for deviceID in Set(deviceIDs) where deviceID != 0 {
            do {
                try delete(deviceID: deviceID)
            } catch let error as OwnerCredentialDeletionError {
                failures[deviceID] = error
            }
        }
        guard failures.isEmpty else {
            throw ProMistLocalDataDeletionError.credentials(failures)
        }
    }
}
